const express = require("express");
const PDFDocument = require("pdfkit");

const {
  formatDate,
  normalizeApplicationData,
  safeFallback,
} = require("../utils/formatters");

const router = express.Router();

const pageMargin = 48;
const cardPadding = 16;
const labelColWidth = 148;
const rowGap = 12;
const sectionGap = 14;
const footerHeight = 42;

const colors = {
  title: "#111827",
  body: "#1F2937",
  muted: "#6B7280",
  border: "#E5E7EB",
  cardBg: "#FFFFFF",
  headerRule: "#E5E7EB",
  badgeBg: "#ECFDF5",
  badgeText: "#047857",
  badgeBorder: "#A7F3D0",
};

function getContentWidth(doc) {
  return doc.page.width - pageMargin * 2;
}

function ensureSpace(doc, requiredHeight) {
  const bottomLimit = doc.page.height - pageMargin - footerHeight;

  if (doc.y + requiredHeight > bottomLimit) {
    doc.addPage();
    doc.y = pageMargin;
  }
}

function drawFooter(doc) {
  const footerY = doc.page.height - pageMargin;
  const width = getContentWidth(doc);

  doc
    .moveTo(pageMargin, footerY - 14)
    .lineTo(pageMargin + width, footerY - 14)
    .lineWidth(0.5)
    .strokeColor(colors.border)
    .stroke();

  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor(colors.muted)
    .text("Generated by Visa AI Assistant", pageMargin, footerY - 8, {
      align: "center",
      width,
    });

  doc.fillColor(colors.body);
  doc.strokeColor("#000000");
}

function drawFootersOnAllPages(doc) {
  const range = doc.bufferedPageRange();

  for (let index = range.start; index < range.start + range.count; index += 1) {
    doc.switchToPage(index);
    drawFooter(doc);
  }
}

function drawStatusBadge(doc, x, y, label) {
  const paddingX = 10;
  const badgeHeight = 20;

  doc.font("Helvetica-Bold").fontSize(8);
  const textWidth = doc.widthOfString(label);
  const badgeWidth = textWidth + paddingX * 2;

  doc
    .roundedRect(x, y, badgeWidth, badgeHeight, 10)
    .fillColor(colors.badgeBg)
    .fill()
    .lineWidth(0.75)
    .strokeColor(colors.badgeBorder)
    .stroke();

  doc
    .fillColor(colors.badgeText)
    .text(label, x + paddingX, y + 6, {
      width: textWidth,
      lineBreak: false,
    });

  doc.fillColor(colors.body);
}

function drawMetaLine(doc, x, y, label, value) {
  doc
    .font("Helvetica")
    .fontSize(8.5)
    .fillColor(colors.muted)
    .text(`${label}`, x, y, { continued: true });

  doc
    .font("Helvetica-Bold")
    .fontSize(8.5)
    .fillColor(colors.body)
    .text(` ${value}`, {
      lineBreak: false,
    });
}

function drawHeader(doc, applicationData) {
  const width = getContentWidth(doc);
  const headerTop = doc.y;
  const applicationId = safeFallback(
    applicationData.applicationId,
    "VA-2026-0001"
  );
  const submissionDate = formatDate(
    String(applicationData.submittedAt).slice(0, 10)
  );

  const badgeLabel = "Submitted";
  doc.font("Helvetica-Bold").fontSize(8);
  const badgeWidth = doc.widthOfString(badgeLabel) + 20;

  doc
    .font("Helvetica-Bold")
    .fontSize(24)
    .fillColor(colors.title)
    .text("Visa Application Summary", pageMargin, headerTop, {
      width: width - badgeWidth - 12,
      lineGap: 2,
    });

  drawStatusBadge(
    doc,
    pageMargin + width - badgeWidth,
    headerTop + 4,
    badgeLabel
  );

  const metaY = headerTop + 34;

  drawMetaLine(doc, pageMargin, metaY, "Application ID", applicationId);
  drawMetaLine(
    doc,
    pageMargin,
    metaY + 14,
    "Submission Date",
    submissionDate
  );

  doc.y = metaY + 34;

  doc
    .moveTo(pageMargin, doc.y)
    .lineTo(pageMargin + width, doc.y)
    .lineWidth(0.75)
    .strokeColor(colors.headerRule)
    .stroke();

  doc.y += 18;
  doc.fillColor(colors.body);
}

function estimateSectionHeight(rows) {
  return cardPadding * 2 + 22 + rows.length * (rowGap + 14) + 8;
}

function drawRow(doc, x, y, label, value) {
  const innerWidth = getContentWidth(doc) - cardPadding * 2;
  const valueWidth = innerWidth - labelColWidth;
  const normalizedValue = safeFallback(value);

  doc.font("Helvetica").fontSize(9.5);
  const labelHeight = doc.heightOfString(label, { width: labelColWidth - 8 });

  doc.font("Helvetica-Bold").fontSize(10.5);
  const valueHeight = doc.heightOfString(normalizedValue, {
    width: valueWidth,
    lineGap: 1,
  });

  const rowHeight = Math.max(labelHeight, valueHeight);

  doc
    .font("Helvetica")
    .fontSize(9.5)
    .fillColor(colors.muted)
    .text(label, x, y, {
      width: labelColWidth - 8,
    });

  doc
    .font("Helvetica-Bold")
    .fontSize(10.5)
    .fillColor(colors.body)
    .text(normalizedValue, x + labelColWidth, y, {
      width: valueWidth,
      lineGap: 1,
    });

  return rowHeight + rowGap;
}

function drawSectionCard(doc, title, rows) {
  ensureSpace(doc, estimateSectionHeight(rows));

  const cardX = pageMargin;
  const cardWidth = getContentWidth(doc);
  const innerX = cardX + cardPadding;
  const startY = doc.y;

  doc.y = startY + cardPadding;

  doc
    .font("Helvetica-Bold")
    .fontSize(12)
    .fillColor(colors.title)
    .text(title, innerX, doc.y, {
      width: cardWidth - cardPadding * 2,
    });

  doc.y += 10;

  let rowY = doc.y;

  rows.forEach(([label, value]) => {
    rowY += drawRow(doc, innerX, rowY, label, value);
  });

  doc.y = rowY;

  const endY = doc.y + cardPadding;

  doc
    .roundedRect(cardX, startY, cardWidth, endY - startY, 8)
    .lineWidth(1)
    .strokeColor(colors.border)
    .stroke();

  doc.y = endY + sectionGap;
  doc.fillColor(colors.body);
}

router.post("/generate-pdf", async (req, res) => {
  try {
    const applicationData = normalizeApplicationData(req.body);

    const {
      passportDetails,
      visaDetails,
      submittedAt,
    } = applicationData;

    if (
      !passportDetails.name ||
      !passportDetails.passportNumber ||
      !passportDetails.nationality ||
      !passportDetails.sex ||
      !passportDetails.dateOfBirth ||
      !visaDetails.destinationCountry ||
      !visaDetails.visaType ||
      !visaDetails.duration
    ) {
      return res.status(400).json({
        message:
          "Complete all required passport and visa details before generating the PDF.",
      });
    }

    const doc = new PDFDocument({
      size: "A4",
      margin: pageMargin,
    });

    res.setHeader("Content-Type", "application/pdf");

    res.setHeader(
      "Content-Disposition",
      "attachment; filename=visa-application.pdf"
    );

    doc.pipe(res);

    drawHeader(doc, applicationData);

    drawSectionCard(doc, "Applicant Information", [
      ["Full Name", safeFallback(passportDetails.name)],
      [
        "Submitted On",
        formatDate(String(submittedAt).slice(0, 10)),
      ],
    ]);

    drawSectionCard(doc, "Passport Information", [
      [
        "Passport Number",
        safeFallback(passportDetails.passportNumber),
      ],
      ["Nationality", safeFallback(passportDetails.nationality)],
      ["Issuing Country", safeFallback(passportDetails.issuingCountry)],
      ["Sex", safeFallback(passportDetails.sex)],
      [
        "Date of Birth",
        passportDetails.dateOfBirth
          ? formatDate(passportDetails.dateOfBirth)
          : "Not Provided",
      ],
      [
        "Expiry Date",
        passportDetails.expiryDate
          ? formatDate(passportDetails.expiryDate)
          : "Not Provided",
      ],
    ]);

    drawSectionCard(doc, "Visa Information", [
      [
        "Destination Country",
        safeFallback(visaDetails.destinationCountry),
      ],
      ["Visa Type", safeFallback(visaDetails.visaType)],
      [
        "Duration of Stay",
        safeFallback(visaDetails.duration),
      ],
      [
        "Travel Date",
        visaDetails.travelDate &&
        visaDetails.travelDate !== "Not sure"
          ? formatDate(visaDetails.travelDate)
          : "Not sure",
      ],
      [
        "Additional Notes",
        safeFallback(
          visaDetails.additionalNotes,
          "Not Provided"
        ),
      ],
    ]);

    drawFootersOnAllPages(doc);

    doc.end();
  } catch (error) {
    console.log(error);

    res.status(500).json({
      message: "Failed to generate PDF",
    });
  }
});

module.exports = router;
