const mrzCountryMap = {
  ABW: { issuingCountry: "Aruba", nationality: "Aruban" },
  AFG: { issuingCountry: "Afghanistan", nationality: "Afghan" },
  AGO: { issuingCountry: "Angola", nationality: "Angolan" },
  AIA: { issuingCountry: "Anguilla", nationality: "Anguillan" },
  ALA: { issuingCountry: "Aland Islands", nationality: "Aland Islander" },
  ALB: { issuingCountry: "Albania", nationality: "Albanian" },
  AND: { issuingCountry: "Andorra", nationality: "Andorran" },
  ARE: { issuingCountry: "United Arab Emirates", nationality: "Emirati" },
  ARG: { issuingCountry: "Argentina", nationality: "Argentine" },
  ARM: { issuingCountry: "Armenia", nationality: "Armenian" },
  ASM: { issuingCountry: "American Samoa", nationality: "American Samoan" },
  ATA: { issuingCountry: "Antarctica", nationality: "Antarctic" },
  ATF: { issuingCountry: "French Southern Territories", nationality: "French Southern Territories" },
  ATG: { issuingCountry: "Antigua and Barbuda", nationality: "Antiguan and Barbudan" },
  AUS: { issuingCountry: "Australia", nationality: "Australian" },
  AUT: { issuingCountry: "Austria", nationality: "Austrian" },
  AZE: { issuingCountry: "Azerbaijan", nationality: "Azerbaijani" },
  BDI: { issuingCountry: "Burundi", nationality: "Burundian" },
  BEL: { issuingCountry: "Belgium", nationality: "Belgian" },
  BEN: { issuingCountry: "Benin", nationality: "Beninese" },
  BES: { issuingCountry: "Bonaire, Sint Eustatius and Saba", nationality: "Dutch Caribbean" },
  BFA: { issuingCountry: "Burkina Faso", nationality: "Burkinabe" },
  BGD: { issuingCountry: "Bangladesh", nationality: "Bangladeshi" },
  BGR: { issuingCountry: "Bulgaria", nationality: "Bulgarian" },
  BHR: { issuingCountry: "Bahrain", nationality: "Bahraini" },
  BHS: { issuingCountry: "Bahamas", nationality: "Bahamian" },
  BIH: { issuingCountry: "Bosnia and Herzegovina", nationality: "Bosnian and Herzegovinian" },
  BLM: { issuingCountry: "Saint Barthelemy", nationality: "Saint Barthelemy" },
  BLR: { issuingCountry: "Belarus", nationality: "Belarusian" },
  BLZ: { issuingCountry: "Belize", nationality: "Belizean" },
  BMU: { issuingCountry: "Bermuda", nationality: "Bermudian" },
  BOL: { issuingCountry: "Bolivia", nationality: "Bolivian" },
  BRA: { issuingCountry: "Brazil", nationality: "Brazilian" },
  BRB: { issuingCountry: "Barbados", nationality: "Barbadian" },
  BRN: { issuingCountry: "Brunei", nationality: "Bruneian" },
  BTN: { issuingCountry: "Bhutan", nationality: "Bhutanese" },
  BVT: { issuingCountry: "Bouvet Island", nationality: "Bouvet Island" },
  BWA: { issuingCountry: "Botswana", nationality: "Motswana" },
  CAF: { issuingCountry: "Central African Republic", nationality: "Central African" },
  CAN: { issuingCountry: "Canada", nationality: "Canadian" },
  CCK: { issuingCountry: "Cocos (Keeling) Islands", nationality: "Cocos Islander" },
  CHE: { issuingCountry: "Switzerland", nationality: "Swiss" },
  CHL: { issuingCountry: "Chile", nationality: "Chilean" },
  CHN: { issuingCountry: "China", nationality: "Chinese" },
  CIV: { issuingCountry: "Cote d'Ivoire", nationality: "Ivorian" },
  CMR: { issuingCountry: "Cameroon", nationality: "Cameroonian" },
  COD: { issuingCountry: "Democratic Republic of the Congo", nationality: "Congolese" },
  COG: { issuingCountry: "Republic of the Congo", nationality: "Congolese" },
  COK: { issuingCountry: "Cook Islands", nationality: "Cook Islander" },
  COL: { issuingCountry: "Colombia", nationality: "Colombian" },
  COM: { issuingCountry: "Comoros", nationality: "Comorian" },
  CPV: { issuingCountry: "Cape Verde", nationality: "Cape Verdean" },
  CRI: { issuingCountry: "Costa Rica", nationality: "Costa Rican" },
  CUB: { issuingCountry: "Cuba", nationality: "Cuban" },
  CUW: { issuingCountry: "Curacao", nationality: "Curacaoan" },
  CXR: { issuingCountry: "Christmas Island", nationality: "Christmas Islander" },
  CYM: { issuingCountry: "Cayman Islands", nationality: "Caymanian" },
  CYP: { issuingCountry: "Cyprus", nationality: "Cypriot" },
  CZE: { issuingCountry: "Czechia", nationality: "Czech" },
  D: { issuingCountry: "Germany", nationality: "German" },
  DEU: { issuingCountry: "Germany", nationality: "German" },
  DJI: { issuingCountry: "Djibouti", nationality: "Djiboutian" },
  DMA: { issuingCountry: "Dominica", nationality: "Dominican" },
  DNK: { issuingCountry: "Denmark", nationality: "Danish" },
  DOM: { issuingCountry: "Dominican Republic", nationality: "Dominican" },
  DZA: { issuingCountry: "Algeria", nationality: "Algerian" },
  ECU: { issuingCountry: "Ecuador", nationality: "Ecuadorian" },
  EGY: { issuingCountry: "Egypt", nationality: "Egyptian" },
  ERI: { issuingCountry: "Eritrea", nationality: "Eritrean" },
  ESH: { issuingCountry: "Western Sahara", nationality: "Sahrawi" },
  ESP: { issuingCountry: "Spain", nationality: "Spanish" },
  EST: { issuingCountry: "Estonia", nationality: "Estonian" },
  ETH: { issuingCountry: "Ethiopia", nationality: "Ethiopian" },
  FIN: { issuingCountry: "Finland", nationality: "Finnish" },
  FJI: { issuingCountry: "Fiji", nationality: "Fijian" },
  FLK: { issuingCountry: "Falkland Islands", nationality: "Falkland Islander" },
  FRA: { issuingCountry: "France", nationality: "French" },
  FRO: { issuingCountry: "Faroe Islands", nationality: "Faroese" },
  FSM: { issuingCountry: "Micronesia", nationality: "Micronesian" },
  GAB: { issuingCountry: "Gabon", nationality: "Gabonese" },
  GBR: { issuingCountry: "United Kingdom", nationality: "British" },
  GBD: { issuingCountry: "United Kingdom", nationality: "British Overseas Territories Citizen" },
  GBN: { issuingCountry: "United Kingdom", nationality: "British National (Overseas)" },
  GBO: { issuingCountry: "United Kingdom", nationality: "British Overseas Citizen" },
  GBP: { issuingCountry: "United Kingdom", nationality: "British Protected Person" },
  GBS: { issuingCountry: "United Kingdom", nationality: "British Subject" },
  GEO: { issuingCountry: "Georgia", nationality: "Georgian" },
  GGY: { issuingCountry: "Guernsey", nationality: "British" },
  GHA: { issuingCountry: "Ghana", nationality: "Ghanaian" },
  GIB: { issuingCountry: "Gibraltar", nationality: "Gibraltarian" },
  GIN: { issuingCountry: "Guinea", nationality: "Guinean" },
  GLP: { issuingCountry: "Guadeloupe", nationality: "Guadeloupean" },
  GMB: { issuingCountry: "Gambia", nationality: "Gambian" },
  GNB: { issuingCountry: "Guinea-Bissau", nationality: "Bissau-Guinean" },
  GNQ: { issuingCountry: "Equatorial Guinea", nationality: "Equatorial Guinean" },
  GRC: { issuingCountry: "Greece", nationality: "Greek" },
  GRD: { issuingCountry: "Grenada", nationality: "Grenadian" },
  GRL: { issuingCountry: "Greenland", nationality: "Greenlandic" },
  GTM: { issuingCountry: "Guatemala", nationality: "Guatemalan" },
  GUF: { issuingCountry: "French Guiana", nationality: "French Guianese" },
  GUM: { issuingCountry: "Guam", nationality: "Guamanian" },
  GUY: { issuingCountry: "Guyana", nationality: "Guyanese" },
  HKG: { issuingCountry: "Hong Kong", nationality: "Hong Kong Chinese" },
  HMD: { issuingCountry: "Heard Island and McDonald Islands", nationality: "Heard and McDonald Islander" },
  HND: { issuingCountry: "Honduras", nationality: "Honduran" },
  HRV: { issuingCountry: "Croatia", nationality: "Croatian" },
  HTI: { issuingCountry: "Haiti", nationality: "Haitian" },
  HUN: { issuingCountry: "Hungary", nationality: "Hungarian" },
  IDN: { issuingCountry: "Indonesia", nationality: "Indonesian" },
  IMN: { issuingCountry: "Isle of Man", nationality: "Manx" },
  IND: { issuingCountry: "India", nationality: "Indian" },
  IOT: { issuingCountry: "British Indian Ocean Territory", nationality: "British Indian Ocean Territory" },
  IRL: { issuingCountry: "Ireland", nationality: "Irish" },
  IRN: { issuingCountry: "Iran", nationality: "Iranian" },
  IRQ: { issuingCountry: "Iraq", nationality: "Iraqi" },
  ISL: { issuingCountry: "Iceland", nationality: "Icelandic" },
  ISR: { issuingCountry: "Israel", nationality: "Israeli" },
  ITA: { issuingCountry: "Italy", nationality: "Italian" },
  JAM: { issuingCountry: "Jamaica", nationality: "Jamaican" },
  JEY: { issuingCountry: "Jersey", nationality: "British" },
  JOR: { issuingCountry: "Jordan", nationality: "Jordanian" },
  JPN: { issuingCountry: "Japan", nationality: "Japanese" },
  KAZ: { issuingCountry: "Kazakhstan", nationality: "Kazakhstani" },
  KEN: { issuingCountry: "Kenya", nationality: "Kenyan" },
  KGZ: { issuingCountry: "Kyrgyzstan", nationality: "Kyrgyzstani" },
  KHM: { issuingCountry: "Cambodia", nationality: "Cambodian" },
  KIR: { issuingCountry: "Kiribati", nationality: "I-Kiribati" },
  KNA: { issuingCountry: "Saint Kitts and Nevis", nationality: "Kittitian and Nevisian" },
  KOR: { issuingCountry: "South Korea", nationality: "South Korean" },
  KWT: { issuingCountry: "Kuwait", nationality: "Kuwaiti" },
  LAO: { issuingCountry: "Laos", nationality: "Lao" },
  LBN: { issuingCountry: "Lebanon", nationality: "Lebanese" },
  LBR: { issuingCountry: "Liberia", nationality: "Liberian" },
  LBY: { issuingCountry: "Libya", nationality: "Libyan" },
  LCA: { issuingCountry: "Saint Lucia", nationality: "Saint Lucian" },
  LIE: { issuingCountry: "Liechtenstein", nationality: "Liechtensteiner" },
  LKA: { issuingCountry: "Sri Lanka", nationality: "Sri Lankan" },
  LSO: { issuingCountry: "Lesotho", nationality: "Basotho" },
  LTU: { issuingCountry: "Lithuania", nationality: "Lithuanian" },
  LUX: { issuingCountry: "Luxembourg", nationality: "Luxembourgish" },
  LVA: { issuingCountry: "Latvia", nationality: "Latvian" },
  MAC: { issuingCountry: "Macao", nationality: "Macanese" },
  MAF: { issuingCountry: "Saint Martin", nationality: "Saint Martin" },
  MAR: { issuingCountry: "Morocco", nationality: "Moroccan" },
  MCO: { issuingCountry: "Monaco", nationality: "Monegasque" },
  MDA: { issuingCountry: "Moldova", nationality: "Moldovan" },
  MDG: { issuingCountry: "Madagascar", nationality: "Malagasy" },
  MDV: { issuingCountry: "Maldives", nationality: "Maldivian" },
  MEX: { issuingCountry: "Mexico", nationality: "Mexican" },
  MHL: { issuingCountry: "Marshall Islands", nationality: "Marshallese" },
  MKD: { issuingCountry: "North Macedonia", nationality: "Macedonian" },
  MLI: { issuingCountry: "Mali", nationality: "Malian" },
  MLT: { issuingCountry: "Malta", nationality: "Maltese" },
  MMR: { issuingCountry: "Myanmar", nationality: "Burmese" },
  MNE: { issuingCountry: "Montenegro", nationality: "Montenegrin" },
  MNG: { issuingCountry: "Mongolia", nationality: "Mongolian" },
  MNP: { issuingCountry: "Northern Mariana Islands", nationality: "Northern Mariana Islander" },
  MOZ: { issuingCountry: "Mozambique", nationality: "Mozambican" },
  MRT: { issuingCountry: "Mauritania", nationality: "Mauritanian" },
  MSR: { issuingCountry: "Montserrat", nationality: "Montserratian" },
  MTQ: { issuingCountry: "Martinique", nationality: "Martiniquais" },
  MUS: { issuingCountry: "Mauritius", nationality: "Mauritian" },
  MWI: { issuingCountry: "Malawi", nationality: "Malawian" },
  MYS: { issuingCountry: "Malaysia", nationality: "Malaysian" },
  MYT: { issuingCountry: "Mayotte", nationality: "Mahoran" },
  NAM: { issuingCountry: "Namibia", nationality: "Namibian" },
  NCL: { issuingCountry: "New Caledonia", nationality: "New Caledonian" },
  NER: { issuingCountry: "Niger", nationality: "Nigerien" },
  NFK: { issuingCountry: "Norfolk Island", nationality: "Norfolk Islander" },
  NGA: { issuingCountry: "Nigeria", nationality: "Nigerian" },
  NIC: { issuingCountry: "Nicaragua", nationality: "Nicaraguan" },
  NIU: { issuingCountry: "Niue", nationality: "Niuean" },
  NLD: { issuingCountry: "Netherlands", nationality: "Dutch" },
  NOR: { issuingCountry: "Norway", nationality: "Norwegian" },
  NPL: { issuingCountry: "Nepal", nationality: "Nepalese" },
  NRU: { issuingCountry: "Nauru", nationality: "Nauruan" },
  NZL: { issuingCountry: "New Zealand", nationality: "New Zealander" },
  OMN: { issuingCountry: "Oman", nationality: "Omani" },
  PAK: { issuingCountry: "Pakistan", nationality: "Pakistani" },
  PAN: { issuingCountry: "Panama", nationality: "Panamanian" },
  PCN: { issuingCountry: "Pitcairn", nationality: "Pitcairn Islander" },
  PER: { issuingCountry: "Peru", nationality: "Peruvian" },
  PHL: { issuingCountry: "Philippines", nationality: "Filipino" },
  PLW: { issuingCountry: "Palau", nationality: "Palauan" },
  PNG: { issuingCountry: "Papua New Guinea", nationality: "Papua New Guinean" },
  POL: { issuingCountry: "Poland", nationality: "Polish" },
  PRI: { issuingCountry: "Puerto Rico", nationality: "Puerto Rican" },
  PRK: { issuingCountry: "North Korea", nationality: "North Korean" },
  PRT: { issuingCountry: "Portugal", nationality: "Portuguese" },
  PRY: { issuingCountry: "Paraguay", nationality: "Paraguayan" },
  PSE: { issuingCountry: "Palestine", nationality: "Palestinian" },
  PYF: { issuingCountry: "French Polynesia", nationality: "French Polynesian" },
  QAT: { issuingCountry: "Qatar", nationality: "Qatari" },
  REU: { issuingCountry: "Reunion", nationality: "Reunionese" },
  ROU: { issuingCountry: "Romania", nationality: "Romanian" },
  RUS: { issuingCountry: "Russia", nationality: "Russian" },
  RWA: { issuingCountry: "Rwanda", nationality: "Rwandan" },
  SAU: { issuingCountry: "Saudi Arabia", nationality: "Saudi Arabian" },
  SDN: { issuingCountry: "Sudan", nationality: "Sudanese" },
  SEN: { issuingCountry: "Senegal", nationality: "Senegalese" },
  SGP: { issuingCountry: "Singapore", nationality: "Singaporean" },
  SGS: { issuingCountry: "South Georgia and the South Sandwich Islands", nationality: "South Georgia and South Sandwich Islander" },
  SHN: { issuingCountry: "Saint Helena, Ascension and Tristan da Cunha", nationality: "Saint Helenian" },
  SJM: { issuingCountry: "Svalbard and Jan Mayen", nationality: "Svalbard and Jan Mayen" },
  SLB: { issuingCountry: "Solomon Islands", nationality: "Solomon Islander" },
  SLE: { issuingCountry: "Sierra Leone", nationality: "Sierra Leonean" },
  SLV: { issuingCountry: "El Salvador", nationality: "Salvadoran" },
  SMR: { issuingCountry: "San Marino", nationality: "Sammarinese" },
  SOM: { issuingCountry: "Somalia", nationality: "Somali" },
  SPM: { issuingCountry: "Saint Pierre and Miquelon", nationality: "Saint-Pierrais and Miquelonnais" },
  SRB: { issuingCountry: "Serbia", nationality: "Serbian" },
  SSD: { issuingCountry: "South Sudan", nationality: "South Sudanese" },
  STP: { issuingCountry: "Sao Tome and Principe", nationality: "Sao Tomean" },
  SUR: { issuingCountry: "Suriname", nationality: "Surinamese" },
  SVK: { issuingCountry: "Slovakia", nationality: "Slovak" },
  SVN: { issuingCountry: "Slovenia", nationality: "Slovenian" },
  SWE: { issuingCountry: "Sweden", nationality: "Swedish" },
  SWZ: { issuingCountry: "Eswatini", nationality: "Swazi" },
  SXM: { issuingCountry: "Sint Maarten", nationality: "Sint Maartener" },
  SYC: { issuingCountry: "Seychelles", nationality: "Seychellois" },
  SYR: { issuingCountry: "Syria", nationality: "Syrian" },
  TCA: { issuingCountry: "Turks and Caicos Islands", nationality: "Turks and Caicos Islander" },
  TCD: { issuingCountry: "Chad", nationality: "Chadian" },
  TGO: { issuingCountry: "Togo", nationality: "Togolese" },
  THA: { issuingCountry: "Thailand", nationality: "Thai" },
  TJK: { issuingCountry: "Tajikistan", nationality: "Tajikistani" },
  TKL: { issuingCountry: "Tokelau", nationality: "Tokelauan" },
  TKM: { issuingCountry: "Turkmenistan", nationality: "Turkmen" },
  TLS: { issuingCountry: "Timor-Leste", nationality: "Timorese" },
  TON: { issuingCountry: "Tonga", nationality: "Tongan" },
  TTO: { issuingCountry: "Trinidad and Tobago", nationality: "Trinidadian and Tobagonian" },
  TUN: { issuingCountry: "Tunisia", nationality: "Tunisian" },
  TUR: { issuingCountry: "Turkey", nationality: "Turkish" },
  TUV: { issuingCountry: "Tuvalu", nationality: "Tuvaluan" },
  TWN: { issuingCountry: "Taiwan", nationality: "Taiwanese" },
  TZA: { issuingCountry: "Tanzania", nationality: "Tanzanian" },
  UGA: { issuingCountry: "Uganda", nationality: "Ugandan" },
  UKR: { issuingCountry: "Ukraine", nationality: "Ukrainian" },
  UMI: { issuingCountry: "United States Minor Outlying Islands", nationality: "American" },
  UNO: { issuingCountry: "United Nations", nationality: "United Nations Official" },
  UNA: { issuingCountry: "United Nations Agency", nationality: "United Nations Agency Official" },
  UNK: { issuingCountry: "United Nations Interim Administration Mission in Kosovo", nationality: "Kosovo Resident" },
  URY: { issuingCountry: "Uruguay", nationality: "Uruguayan" },
  USA: { issuingCountry: "United States", nationality: "American" },
  UZB: { issuingCountry: "Uzbekistan", nationality: "Uzbekistani" },
  VAT: { issuingCountry: "Vatican City", nationality: "Vatican" },
  VCT: { issuingCountry: "Saint Vincent and the Grenadines", nationality: "Vincentian" },
  VEN: { issuingCountry: "Venezuela", nationality: "Venezuelan" },
  VGB: { issuingCountry: "British Virgin Islands", nationality: "British Virgin Islander" },
  VIR: { issuingCountry: "United States Virgin Islands", nationality: "U.S. Virgin Islander" },
  VNM: { issuingCountry: "Vietnam", nationality: "Vietnamese" },
  VUT: { issuingCountry: "Vanuatu", nationality: "Ni-Vanuatu" },
  WLF: { issuingCountry: "Wallis and Futuna", nationality: "Wallisian and Futunan" },
  WSM: { issuingCountry: "Samoa", nationality: "Samoan" },
  XBA: { issuingCountry: "African Development Bank", nationality: "African Development Bank" },
  XCC: { issuingCountry: "Caribbean Community", nationality: "Caribbean Community" },
  XCO: { issuingCountry: "Common Market for Eastern and Southern Africa", nationality: "COMESA" },
  XDC: { issuingCountry: "Southern African Development Community", nationality: "Southern African Development Community" },
  XEC: { issuingCountry: "Economic Community of West African States", nationality: "ECOWAS" },
  XIM: { issuingCountry: "African Export-Import Bank", nationality: "African Export-Import Bank" },
  XKX: { issuingCountry: "Kosovo", nationality: "Kosovar" },
  XOM: { issuingCountry: "Sovereign Military Order of Malta", nationality: "Sovereign Military Order of Malta" },
  XPO: { issuingCountry: "Interpol", nationality: "Interpol" },
  XXA: { issuingCountry: "Stateless Person", nationality: "Stateless Person" },
  XXB: { issuingCountry: "Refugee", nationality: "Refugee" },
  XXC: { issuingCountry: "Refugee", nationality: "Refugee" },
  XXX: { issuingCountry: "Unspecified", nationality: "Unspecified" },
  YEM: { issuingCountry: "Yemen", nationality: "Yemeni" },
  ZAF: { issuingCountry: "South Africa", nationality: "South African" },
  ZMB: { issuingCountry: "Zambia", nationality: "Zambian" },
  ZWE: { issuingCountry: "Zimbabwe", nationality: "Zimbabwean" },
};

function normalizeMrzCode(value = "") {
  return String(value).trim().toUpperCase().replace(/</g, "").replace(/[^A-Z]/g, "");
}

function getMrzCountryEntry(value = "") {
  return mrzCountryMap[normalizeMrzCode(value)] || null;
}

function isValidMrzCountryCode(value = "") {
  const code = normalizeMrzCode(value);

  // ICAO permits some non-country/special values, but XXX is an
  // unspecified placeholder. Treat it like OCR noise for display purposes.
  return Boolean(code && code !== "XXX" && mrzCountryMap[code]);
}

function normalizeMrzIssuingCountry(value = "") {
  const entry = isValidMrzCountryCode(value) ? getMrzCountryEntry(value) : null;
  return entry ? entry.issuingCountry : "";
}

function normalizeMrzNationality(value = "") {
  const entry = isValidMrzCountryCode(value) ? getMrzCountryEntry(value) : null;
  return entry ? entry.nationality : "";
}

module.exports = {
  mrzCountryMap,
  getMrzCountryEntry,
  isValidMrzCountryCode,
  normalizeMrzCode,
  normalizeMrzIssuingCountry,
  normalizeMrzNationality,
};
